version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq

  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - features
      - rabbitmq

  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - model
      - rabbitmq
    volumes:
      - ./logs:/app/logs

  plot:
    build:
      context: ./plot
    restart: always
    depends_on:
      - metric
    volumes:
      - ./logs:/app/logs