version: '3.8'
services:
  my-service:
    image: $CI_REGISTRY_IMAGE/my-service:$CI_COMMIT_SHORT_SHA
    ports:
      - "8080:8080"  # Ports may vary, put here yours 
    environment:
      - ENV_VAR=production